### ISSUE TITLE
The integration can't be uninstalled

### ISSUE THREAD

**Issue by mottwan** [elupus/hass_media_stack#1]
![image](https://user-images.githubusercontent.com/2526397/117417668-41f19680-af23-11eb-9c9e-2a197d81b9d0.png)

**Comment by elupus** [comment]
That sounds like a hacs issue. The integration provide no such feature.

**Comment by mottwan** [comment]
> That sounds like a hacs issue. The integration provide no such feature.

All the other custom integrations are easily uninstalled

**Comment by elupus** [comment]
Yes that would be a feature of HACS. Not of this integration. It provides no such feature.
