### ISSUE TITLE
Installation location of the media stack integration does not create a dedicated folder 

### ISSUE THREAD

**Issue by mottwan** [elupus/hass_media_stack#2]
After installing the media stack integration in custom_compontents sould be created a new folder "media_stack"
|_ - "custom_components"
  |_ - "media_stack"
    |_ - \_\_init\_\_.py
        - manifest.json
        - media_player.py
Now I have:
      |_ - "custom_components"
        |_ - \_\_init\_\_.py
           - manifest.json
           - media_player.py

![image](https://user-images.githubusercontent.com/2526397/117423721-b3344800-af29-11eb-87c7-b7ace0a0d792.png)

**Comment by elupus** [comment]
Then you or hacs installed in wrongly.

**Comment by mottwan** [comment]
Nope, I installed the HACS following their official instruction
The issue is in **hass_media_stack/custom_components/\_\_init\_\_.py**  from custom_components folder it should be removed

**Comment by mottwan** [comment]
> Nope, I installed the HACS following their official instruction
> The issue is in **hass_media_stack/custom_components/\_\_init\_\_.py** from custom_components folder it should be removed

this will fix and the following issues as well https://github.com/elupus/hass_media_stack/issues/1

**Comment by mottwan** [comment]
https://github.com/elupus/hass_media_stack/issues/2#issuecomment-834205959
@elupus ^

**Comment by elupus** [comment]
Hmm. That init is needed for tests.

**Comment by mottwan** [comment]
> Hmm. That init is needed for tests.

just add it in .gitignore and leave it locally

**Comment by elupus** [comment]
Well.. eh no. Then ci won't work

**Comment by elupus** [comment]
According to hacs devs. This setup is fine. So I'm closing this.
