### ISSUE TITLE
Hassio Log error Could not read manifest.json caused by last line(version) comma

### ISSUE THREAD

**Issue by mottwan** [elupus/hass_media_stack#3]
Pls remove comma from the end of version line 
![image](https://user-images.githubusercontent.com/2526397/117431085-7cfac680-af31-11eb-994e-378141c5cb1e.png)
![image](https://user-images.githubusercontent.com/2526397/117423891-dbbc4200-af29-11eb-988d-72d63e1e5fa3.png)

**Comment by elupus** [comment]
Fixed
